### ISSUE TITLE
Trusted Computing Platform Alliance: The Motherboard of all Big Brothers

### ISSUE THREAD

**Issue by Atavic** [CHEF-KOCH/NSABlocklist#5] opened 2016-09-09 19:24 UTC
The _Trusted Computing Group_ is an alliance that puts hardware modules in modern motherboards, enabled on Linux systems with systemd [*], on Microsoft systems they appear
as Trusted Platform Module (TPM) services.

> https://en.wikipedia.org/wiki/Trusted_Computing#Loss_of_anonymity
> Because a Trusted Computing equipped computer is able to uniquely attest to its own identity, it will be possible for vendors and others who possess the ability to use the attestation feature to zero in on the identity of the user of TC-enabled software with a high degree of certainty. 

At page 7 of _Lucky Green PDF_ there's a list of TCPA 170 Member Companies:
http://www.cypherpunks.to/TCPA_DEFCON_10.pdf

The list could be added in NSABlocklist© project's README.md under
## Providers

 [*] Trusted Computing Platform in systemd:
https://github.com/systemd/systemd/blob/09541e49ebd17b41482e447dd8194942f39788c0/src/boot/efi/measure.c

**Comment by Atavic** [comment] 2016-10-04 17:04
As a counterpart to _Lucky Green PDF_, [here](www.nist.gov/standardsgov/upload/TCG.pdf) is another Doc from nist site.

TCG uses [DAA](https://www.zurich.ibm.com/security/daa/).

**Comment by CHEF-KOCH** [comment] 2016-10-05 04:37
I'm investigating in this since ~ 1 year now, it's difficult to show proof and now only possible or theoretically attacks. In real world there is not any known attack to this (officially). 

I also search for UEFI backdoors and such kind of things, but from what I know no one use this in real world or if only FBI and such agancies. It's not practicable attack since it needs physically access (which is impossible to secure) [without destroying hardware itself].

**Comment by Atavic** [comment] 2016-10-06 18:01
I think we are in the same league: I looked at the staggering potential of these TPM Chips and they have a feature called _Rogue TPM Tagging_:

> TPMs should be produced tamper-resistance. Otherwise, the whole eﬀorts of trusted computing platforms become meaningless. Even though, if in extreme circumstances, a TPM is compromised and its keypair is being exposed, veriﬁers should be able to identify the attestation requests from a rogue TPM. To do so, the AAKs (Anonymous Authentication Key) of exposed TPMs should be published on the revocation list.

**Comment by Atavic** [comment] 2017-02-22 03:14
A guy who came to InfoSec from BIOS modding community removes the UEFI network stack:
https://github.com/NikolajSchlej/ZeroNights2015

Papers by a Reverse Engineering _subreddit_ moderator:
https://github.com/skochinsky/papers

**Comment by CHEF-KOCH** [comment] 2017-09-03 16:40
The main question remains, which CPU manufacture is 'trustworthy'. 

On one side we have Intel with MEI, which is not removable (no it's not before someone argue that there exist two projects .. 'mei cleaner' and the new one which sets the [bits to 0](https://gist.github.com/CHEF-KOCH/af96c3a63a026b808f09497d136996df)) due the fact there too complicated, there exist no easy to use tool, there is no guarantee that it really works + you have to re-apply it each time you re-install the OS/Bios.

[LibreBoot](https://libreboot.org/faq.html) is also not an option, because it only works with Linux and only with older CPU gens. As explained in their FAQ. 

[AMD also have a similar technology which acts like MEI](https://www.reddit.com/r/security/comments/4ot223/do_amdprocessors_have_something_like_intel/). So, I dunno if it's really an option to 'recommed' AMD. At the end I do not trust both.

**Comment by Atavic** [comment] 2017-09-03 17:22
Going geek with libreboot appears to be the only viable option today.

**Comment by CHEF-KOCH** [comment] 2017-09-03 17:23
[Not really](https://libreboot.org/docs/hardware/#list-of-supported-hardware).

**Comment by Atavic** [comment] 2017-09-03 17:39
Yes, a few options.

**Comment by CHEF-KOCH** [comment] 2018-01-06 07:04
Hardware based attacks:

- https://chefkochblog.wordpress.com/2018/01/05/trackmageddon-gps-location-tracking-services-leaving-user-data-open-to-hackers/
- https://chefkochblog.wordpress.com/2018/01/05/meltdown-and-spectre-almost-everything-gets-patched/
- https://chefkochblog.wordpress.com/2018/01/03/another-huge-intel-bug/
- https://chefkochblog.wordpress.com/2017/12/20/tls-1-3-gets-blocked-by-cisco-avast-nsa/

I will update and merge this into the NSABlocklist soon, it deserves a mention and some guidance how to work this out (if possible), however since this is all new (yes everything under 6 months is new because it takes a lot of time to inspect/audit the issues) I consider to stay calm and see this objective, it doesn't help to make a complaint without teaching peoples anything.

**Comment by CHEF-KOCH** [comment] 2018-05-02 23:27
I need to close this topic after half year doing research I not found any evidence that TPM (especially 2.0) suffers from the following mentioned 'concern' (from Wikipedia):

> TCG has faced resistance to the deployment of this technology in some areas, where some authors see possible uses not specifically related to Trusted Computing, which may raise privacy concerns. The concerns include the abuse of remote validation of software (where the manufacturer‍—‌and not the user who owns the computer system‍—‌decides what software is allowed to run) and possible ways to follow actions taken by the user being recorded in a database, in a manner that is completely undetectable to the user.

1. This is more a OEM specific thing rather than an TPM related issue according to my own research. In fact they try to block the interception in general with locked bootloaders e.g. on ARM devices but this also affects their own software. The biggest proof here is well known, Android 'ROM's'. There is however already since years a problem which is not a concern it's a fact that for example Google Play Store can remotely based on your current user (or user account) remove 'potential apps' once it was removed from the Store + together with checks like SafetyNet + PlayProtect which even submitting like a AV product checksum, IP etc. in order to identify the 'uploader' + the app itself. The normal user can't intercept into it without altering the booloader/su/selinux security ring in order to e.g. modify/block/remove it. I see this much more critical since this 'counter measures' to defeat malware expose you. Windows has a similar scanning called SmartScreen and even some Browser in combination with extension have also such functions. This is far more 'realistic' (well it's a fact) then the need to altering the TPM ring. 
2. Attacking TPM needs [administrator privileges](https://veracrypt.codeplex.com/wikipage?title=FAQ) + physically access. I see those arguments as ineffective in the whole discussion because once an attacker has such access we simply can't speak of 'security' anymore. 
3. [Coppersmith's attack](https://en.wikipedia.org/wiki/Coppersmith%27s_attack) was or is imho more realistic but it should be clearily mentioned that this affects RSA directly. However, the point is that no one uses anymore 1024-bit RSA keys. The today hardware at least use 2048/4096 or ECC instead since this isn't affected at all. 

> The private endorsement key is fundamental to the security of the TPM circuit, and is never made available to the end-user. This private key must be known to the hardware chip manufacturer at manufacture time, otherwise they would not be able to burn the key into the circuit. There are no guarantees that this private key is not kept by the manufacturer or shared with government agencies. Anyone with access to the private endorsement key would be able to forge the chip's identity and break some of the security that the chip provides. Thus, the security of the TPM relies entirely on the manufacturer and the authorities in the country where the hardware is produced.

Wikipedia nor I found any research or proof for this, I also already started a discussion on the Wikipedia site about this. I think the more important part is that [TPM 1.2 is weak and that's the only thing which is confirmed](https://web.archive.org/web/20120130095246/https://www.networkworld.com/news/2010/020210-black-hat-processor-security.html). I find [this old article interesting](https://redmondmag.com/articles/2013/08/22/windows-8-security-issues.aspx) because it summerize it very well:

> It is also important to note that any user concerns about TPM 2.0 are addressable. The first concern, generally expressed as "lack of user control," is not correct as OEMs have the ability to turn off the TPM in x86 machines; thus, purchasers can purchase machines with TPMs disabled (of course, they will also be unable to utilize the security features enabled by the technology). The second concern, generally expressed as "lack of user control over choice of operating system," is also incorrect. In fact, Windows has been designed so that users can clear/reset the TPM for ownership by another OS of they wish. Many TPM functions can also be used by multiple OSes (including Linux) concurrently.

However, I haven't found any document on the NSA leaks or on the internet which goes deep into details about this whole topic. There is a lot of guessing an attention whoring and at the end the normal user already accepted it with Android /ARM at the end. Of course you can bypass everything and there are always ways but most people don't go this way, especially also not beginners or if you device still has warranty (from my experience people wait till warrenty is lost or they not getting security updates anymore until they unlock something) - only a handful people I know 'jailbreak/root/hack/etc' the device in order to 'take control back'. 

It should be mentioned that we not need to talk about such topics in general on closed systems because you never know what is really shared unless you audit/reverse-engineer something to check it. I guess the bigger thread are lots of other things which where shown with the entire leaks. 

So overall I close this now, add the knownm papers, if there is something additional to it I'll add it on the Readme or the Documents section but it's definitly not like in the movies that NSA or other agencies get all keys by using TPM especially because there is no sign of it and even if it takes lot of other hurdles to break your entire security setup and why spent that much effort if there well known other techniques which are more efficent in order to get you?

Coreboot or libreboot?
Well, Coreboot is open source but it requires a few pieces of proprietary firmware in it in order to work with modern professors. The ME is still included in Coreboot because the processor won't run without it. Apparantly me-cleaner removes nearly everything except the parts that the processor needs to run. There's probably other forks of Coreboot that do this, but Libreboot is the most well known one afaik. The problem with [libreboot seems that it's dead](https://www.reddit.com/r/libreboot/comments/7b7wyp/libreboot_seams_dead_some_advice/) and the hardware support is more than limited. However, the libre version of coreboot with the unfree parts stripped away should be preffered (on older hardware).

The biggest problem I see is that even if the idea is great, such project suffering from a lot of problems, financial, hardware support and other things especially internal fights. However, even this can easily defeated with for example HDD implemented malware.

Ref:
* https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/disabling-secure-boot
* https://www.xda-developers.com/microsofts-debug-mode-flaw-and-golden-key-leak-allows-disabling-of-secure-boot/
* https://www.techpowerup.com/209925/nsa-hides-spying-backdoors-into-hard-drive-firmware.html
* https://nakedsecurity.sophos.com/2014/05/14/nsa-intercepts-routers-servers-to-slip-in-backdoors-for-overseas-surveillance/
* http://www.washingtonsblog.com/2013/06/microsoft-programmed-in-nsa-backdoor-in-windows-by-1999.html
* http://arstechnica.com/security/2013/10/meet-badbios-the-mysterious-mac-and-pc-malware-that-jumps-airgaps/
* https://blog.kaspersky.com/equation-hdd-malware/7623/
* https://en.wikipedia.org/wiki/Coreboot
* https://www.coreboot.org/Hardware_Comparison/Libreboot_compatible_laptops
* https://github.com/Cr4sh/SmmBackdoor
* https://yro.slashdot.org/story/17/01/08/1822204/richard-stallman-acknowledges-libreboot-is-no-longer-a-part-of-gnu
* https://link.springer.com/book/10.1007/978-1-4302-6572-6
* https://github.com/librecore-org/librecore-build
* https://www.coreboot.org/Binary_situation

**Closed by CHEF-KOCH** 2018-05-02 23:27 UTC
Labels: Enhancement, Investigating
